### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by bl4ck3agl3** [reteps/arbitrage-moments#9]
hi when i try to start it i get the following error. used to work well in january/february.

`C:\Users\Aldo\AppData\Local\Programs\Python\Python36>python.exe ./start --exchanges Binance Kucoin Etherdelta Cryptopia Bittrex Bitfinex Poloniex --pairs ETH BTC LTC
Traceback (most recent call last):
  File "./start", line 20, in <module>
    cmc = pymarketcap.Pymarketcap()
  File "C:\Users\Aldo\AppData\Local\Programs\Python\Python36\lib\site-packages\pymarketcap\core.py", line 54, in __init__
    self.correspondences = self._cache_symbols()
  File "C:\Users\Aldo\AppData\Local\Programs\Python\Python36\lib\site-packages\pymarketcap\core.py", line 87, in _cache_symbols
    currencies = self.session.get(url).json()
  File "C:\Users\Aldo\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "C:\Users\Aldo\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Aldo\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Aldo\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by reteps** [comment]
sorry, i'll work on it. keep you updated.

**Comment by reteps** [comment]
fixed in commit.
